# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Billmind < Formula
  desc "Terminal app for tracking subscriptions and recurring payments"
  homepage "https://github.com/curkan/billmind"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/curkan/billmind/releases/download/v0.1.0/billmind_Darwin_x86_64.tar.gz"
      sha256 "e3adb43badc0fdf61dac511f65870afed49277763e723623dedb8a782db35f2f"

      def install
        bin.install "billmind"
      end
    end
    on_arm do
      url "https://github.com/curkan/billmind/releases/download/v0.1.0/billmind_Darwin_arm64.tar.gz"
      sha256 "3262697fc7caf57ebc0f8036ced3421abe708b2426eaf881fd4283970f7a04ab"

      def install
        bin.install "billmind"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curkan/billmind/releases/download/v0.1.0/billmind_Linux_x86_64.tar.gz"
        sha256 "4e8ae51f39322c692fca1b9e693205eb4d46cff6fd6331b97abec1649d1184b9"

        def install
          bin.install "billmind"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curkan/billmind/releases/download/v0.1.0/billmind_Linux_arm64.tar.gz"
        sha256 "72aeeec7b43c799ee44836ddc326c770f3e4a2ac08011bc9393b7b8d183d89e8"

        def install
          bin.install "billmind"
        end
      end
    end
  end
end
