# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Go2fa < Formula
  desc ""
  homepage "https://github.com/curkan/homebrew-public"
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://github.com/curkan/go2fa/releases/download/v0.1.4/go2fa_Darwin_x86_64.tar.gz"
      sha256 "a532c1c67eaa28209643a5a8b1df6171052e7df40a9b2ba8106bf86b0444dbde"

      def install
        bin.install "go2fa"
      end
    end
    on_arm do
      url "https://github.com/curkan/go2fa/releases/download/v0.1.4/go2fa_Darwin_arm64.tar.gz"
      sha256 "276ff9b010462c11c05990f7bc7768489dc3b8c5da38156a9912f1c417d9f61a"

      def install
        bin.install "go2fa"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curkan/go2fa/releases/download/v0.1.4/go2fa_Linux_x86_64.tar.gz"
        sha256 "f391e487d206c58f500394760f0ea1990e564908cbc13c400e48d9384c25fca4"

        def install
          bin.install "go2fa"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curkan/go2fa/releases/download/v0.1.4/go2fa_Linux_arm64.tar.gz"
        sha256 "484f1dc6bc74bbd3a49489d82695d201174e4c42162b20c5fed3f780ff066c09"

        def install
          bin.install "go2fa"
        end
      end
    end
  end
end
