# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotickets < Formula
  desc ""
  homepage "https://github.com/curkan/homebrew-public"
  version "2.4.1"

  on_macos do
    on_intel do
      url "https://github.com/curkan/go-tickets/releases/download/v2.4.1/gotickets_Darwin_x86_64.tar.gz"
      sha256 "81268a8ed0e652bf2d12ce5e37cd71b5aca5945c144aacb6f07e1efe24e623f6"

      def install
        bin.install "gotickets"
      end
    end
    on_arm do
      url "https://github.com/curkan/go-tickets/releases/download/v2.4.1/gotickets_Darwin_arm64.tar.gz"
      sha256 "d4b492ef136369dd4bd829f8d2f0f3872b8b21e8f6c131f64bb4b9502d709d35"

      def install
        bin.install "gotickets"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curkan/go-tickets/releases/download/v2.4.1/gotickets_Linux_x86_64.tar.gz"
        sha256 "b4b5ba6a31abd31bb348843d1736b57e14610bd4304090efc4e1cc2763e754c4"

        def install
          bin.install "gotickets"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curkan/go-tickets/releases/download/v2.4.1/gotickets_Linux_arm64.tar.gz"
        sha256 "1902944a557245e5ddb2ccc5a9082f9656493aaeb46a493a4e8576d17b02d8f3"

        def install
          bin.install "gotickets"
        end
      end
    end
  end
end
