# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotickets < Formula
  desc ""
  homepage "https://github.com/curkan/homebrew-public"
  version "2.5.2"

  on_macos do
    on_intel do
      url "https://github.com/curkan/go-tickets/releases/download/v2.5.2/gotickets_Darwin_x86_64.tar.gz"
      sha256 "fdea4434685176cf2cfadb2a72c0f0fca1e95f6c6e08cf98d821b06f3dd8af98"

      def install
        bin.install "gotickets"
      end
    end
    on_arm do
      url "https://github.com/curkan/go-tickets/releases/download/v2.5.2/gotickets_Darwin_arm64.tar.gz"
      sha256 "c0924ed0fef63e70ad60f339a702d2d46665f3f7212e76506fc1fdb18de70636"

      def install
        bin.install "gotickets"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curkan/go-tickets/releases/download/v2.5.2/gotickets_Linux_x86_64.tar.gz"
        sha256 "3274484e112fb83bf011f474074684a3a3ce7e34f0f9260cc2d5873a285a7260"

        def install
          bin.install "gotickets"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curkan/go-tickets/releases/download/v2.5.2/gotickets_Linux_arm64.tar.gz"
        sha256 "7c7601410c9f839098eefe7e19db331156a16ee0c50349fead08dc9c0e373db3"

        def install
          bin.install "gotickets"
        end
      end
    end
  end
end
