# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotickets < Formula
  desc ""
  homepage "https://github.com/curkan/homebrew-public"
  version "2.4.0"

  on_macos do
    on_intel do
      url "https://github.com/curkan/go-tickets/releases/download/v2.4.0/gotickets_Darwin_x86_64.tar.gz"
      sha256 "adfd362cbe0d4227c131ddaab24bf7dad30cc78edcfd87629a62e617926ef623"

      def install
        bin.install "gotickets"
      end
    end
    on_arm do
      url "https://github.com/curkan/go-tickets/releases/download/v2.4.0/gotickets_Darwin_arm64.tar.gz"
      sha256 "1a2b13ab6c1f19994baf941d1af5c72ae5a3dd51056614dfddce5cbcad4f0115"

      def install
        bin.install "gotickets"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curkan/go-tickets/releases/download/v2.4.0/gotickets_Linux_x86_64.tar.gz"
        sha256 "2b1ea131abbbe9c0f3a6ae2f0ebd953937375ca2c28195f240cb58ad84af5dd8"

        def install
          bin.install "gotickets"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curkan/go-tickets/releases/download/v2.4.0/gotickets_Linux_arm64.tar.gz"
        sha256 "8bf832ead3da45c66d3fe0399f51030f0c468510c5907ff7765f3151af8d3ceb"

        def install
          bin.install "gotickets"
        end
      end
    end
  end
end
